# ------------------------------------------------
# Version Status
# ------------------------------------------------
#
# Se usa para verificar en el API status deployments
#
ce.version=1.0.4

# Logger
logger.category=ce-logger
#